CREATE TABLE `tbl_users` (
    `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Username` VARCHAR(50) NOT NULL UNIQUE,
    `Password` VARCHAR(255) NOT NULL,
    `RegDate` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
